#!/bin/bash
if [ -z "${CLJ_EVN}" ]; then
  export CLJ_EVN=${1:-production}
fi

if [ -z "${PORT}" ]; then
  export PORT=${2:-3000}
fi

java -cp target/clojure-template.jar clojure.main -m clojure-template.server